![slicing_img](images/numpy_2D_slicing_diagram_task.png)

In [9]:
a = np.arange(11, 36).reshape(5, 5)
# explanation: comma separates the arrays and colon does the positional selection
# 2dArray[rows, columns]
# double colon: get every n^th value e.g. ::2 menas print every second value and 2::3 means get every third value starting from third pos.
red    = a[0, 1:4]  # get one-dim. subarray of row 0, start:1 (pos=2) end:4 (not included, pos=4)
blue   = a[1:4, 0]  # get one-dim. subarrays (index 1,2,3) of column 0
green  = a[::2,::2] # get a two-dim. subarray of every second element by row and column
purple = a[:, 1]    # get the second column

print('red:',red,'\nblue:',blue,'\ngreen:\n',green,'\npurple:',purple)

red: [12 13 14] 
blue: [16 21 26] 
green:
 [[11 13 15]
 [21 23 25]
 [31 33 35]] 
purple: [12 17 22 27 32]


### Class exercise: table
![](images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [2]:
import numpy as np
a = np.arange(10, 30).reshape(4, 5)
red    = a[0, 1:4] 
white_blue   = a[:,1::2]  
green  = a[0:3, 2]  
blue = a[::2, 4] 

print('red:\n',red,'\nwhite_blue:\n',white_blue,'\ngreen:\n',green,'\nblue:\n',blue)


red:
 [11 12 13] 
white_blue:
 [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
green:
 [12 17 22] 
blue:
 [14 24]


### 3D
reshape can be done with multiple dimensions. Here is an example with 3d  
`a = np.arange(0, 27).reshape((3, 3, 3))`  
![](images/cube.png)

In [11]:
a = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)
#print('whole cube: \n',a, '\n---------------')

print('1st row (x-values): \n',a[0,0,:],'\n---------')
print('1st collumn (y-values, where x==0): \n',a[0,:,0],'\n---------')
print('1st depth (z-values, where y==0 and x==0): \n',a[:,0,0],'\n---------')
print('value of first side, second slice, third piece:\n',a[0, 1, 2], '\n-------------')  # equal to a[0][1][2] = 5
print('values of all x*z where y=2\n',a[:,2], '\n----------')  # equivivalent to a[:,2,:] all z, y=2, all x.
print('all z and y values where x = 2: \n',a[:,:,2], '\n--------')  # 
print('skip each second z,y,x: \n',a[::2,::2,::2])  # all z (skip each second) and all y (skip each second) etc.

1st row (x-values): 
 [0 1 2] 
---------
1st collumn (y-values, where x==0): 
 [0 3 6] 
---------
1st depth (z-values, where y==0 and x==0): 
 [ 0  9 18] 
---------
value of first side, second slice, third piece:
 5 
-------------
values of all x*z where y=2
 [[ 6  7  8]
 [15 16 17]
 [24 25 26]] 
----------
all z and y values where x = 2: 
 [[ 2  5  8]
 [11 14 17]
 [20 23 26]] 
--------
skip each second z,y,x: 
 [[[ 0  2]
  [ 6  8]]

 [[18 20]
  [24 26]]]


### Class exercise: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [4]:
import numpy as np
a = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)
ex1    = a[1,1,:]
ex2   = a[0:3,1,0]
ex3   = a[0,:,2]

print(a)
print("\n\nEx1\n",ex1)
print("\n\nEx2\n",ex2)
print("\n\nEx3\n",ex3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Ex1
 [12 13 14]


Ex2
 [ 3 12 21]


Ex3
 [2 5 8]


### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6
  - using the operators: `%` and `|` mask to only get numbers that are divisible by 3 and numbers begining with 8


## Exercise numpy and csv

1. load the csv file: befkbhalderstatkode.csv into a numpy ndarray
2. How many german children were 0 years old in 2015?
3. create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data
4. create a new function like previous so that it can sum values for all ages if age is not provided to the function
5. further add functionality to sum values if citizenship or area was not provided to function.
6. create a new function that can also give average values for each year if year whas not provided.
7. create a function, that given year and nationality can return which area had the most of these nationals by that year. Test it by finding out which area had the most Moroccan people in both 1992 and 2015
8. Find the Area(s) where fewest foreingers lived in Copenhagen in 1992 and 2015 respectively
9. Find out what age most French people have in 2015

## class exercise: extracting
Based on the Copenhagen population data do the following (not including danish citizens):
1. Find the 10 largest population groups
2. Find the 10 largest population groups of children (0-17 y.o.) 
3. Create a barplot with the 10 largest groups on x-axis and 2 bars of both adult and children on y-axis
  - make one bar red and the other green
  - give them labels